---
title: "Домашка по теории вероятностей"
author: "Винни-Пух"
date: "21 ноября 2016"
output: pdf_document
fontsize: 11pt
lang: ru-RU
---

Задачи:

1. Возьми любой интересный тебе набор данных. Абсолютно любой. И представь его графический анализ. Больше разных графиков! Покажи, что ты адепт ggplot, демон Seaborn или богиня Bokeh! 

    - Если не хочешь, чтобы твоя работа была предана огню сразу, то откажись от круговых диаграмм и графиков с 3d-рюшечками.
    - Помни, что хороший график отлично читается, если его вырезать из работы. Подпиши оси, укажи единицы измерения.
    - Вдохновляйся красотой. Сходи в Третьяковку, Алмазный фонд или хотя бы загугли `seaborn python` и выбери вкладку `Images`. 
    - После каждого графика напиши одну-две фразы с описанием.
    - Десять графиков хватит!
  
2. Занудная симуляционная задача. Пусть $X_i$ независимы и равномерны на $[0;1]$.   

    1. Нарисуй гистограмму распределения для $X_1$, $X_1 + X_2 + X_3$, $\sum_{i=1}^{10} X_i$, $\sum_{i=1}^{50} X_i$
    1. Оцени $P(X_1 + X_2 + X_3 > 2)$
    1. Оцени $E(X_1^5)$, $Var(X_1 / 1 + X_2^2)$
    1. Оцени медиану и 25\%-ую квантиль для $(1+X_1) / (3 + X_2)$

3. Любая задача без решения из подборки красивых задач по теории вероятностей, \url{https://github.com/bdemeshev/probability_dna/}. 

    - Оценка за задачу делится на количество её решивших, поэтому лучше договорись с одногруппниками :)
    - Задачи, у которых есть короткий ответ, но нет решения, тоже можно брать!
    - Реши задачу самостоятельно, если не получается решить — загугли, если не получается загуглить — спроси у меня, если опять не повезло — да пребудет с тобой \url{http://math.stackexchange.com/}!


Формальности:

1. Домашка изготовляется в формате `.ipynb`. 

2. Домашка сдаётся в двух видах: в печатном на семинаре, в электронном высылается на `boris.demeshev@gmail.com`. Тема письма должна быть ровно `pr201: hometask`. 

3. Срок сдачи: 22 декабря 2016 года
