

Листок 1 по ТВ и МС 2013--2014 [08.03.2014]





1

Кафедра математической экономики и эконометрики НИУ ВШЭ. Борзых Д. А.

Листок 1

Общие сведения о дискретных случайных величинах



\textbf{Задача 1.} Пусть $\Omega =\{ a,b,c,d\} $, ${\rm {\mathbb P}}(\{ a\} )=\ldots ={\rm {\mathbb P}}(\{ d\} )=1/4$ и случайная величина $X:\Omega \to {\mathbb R}$ задана при помощи следующей таблицы.

\begin{tabular}{|p{0.3in}|p{0.3in}|p{0.3in}|p{0.3in}|p{0.3in}|} \hline 
$\Omega $ & $a$ & $b$ & $c$ & $d$ \\ \hline 
$X$ & $-1$ & $0$ & $0$ & $1$ \\ \hline 
\end{tabular}



\begin{enumerate}
\item  Найдите $\{ \omega \in \Omega :X(\omega )\ge 0\} $.

\item  Найдите ${\rm {\mathbb P}}(\{ \omega \in \Omega :X(\omega )\ge 0\} )$.

\item  Найдите ${\rm {\mathbb P}}(\{ \omega \in \Omega :|X(\omega )|\, =1\} )$.

\item  Постройте графики функций распределения случайных величин $X$, $X+1$ и $X^{2} $.

\item  Найдите ${\rm {\mathbb E}}[X]$, ${\rm {\mathbb E}}[X^{2} ]$ и ${\rm {\mathbb E}}[X^{4} ]$.

\item  Найдите $D(X)$, $D(X+1)$ и $D(X^{2} )$.

\item  Постройте таблицы распределения случайных величин $X$, $X+1$ и $X^{2} $.
\end{enumerate}

\textbf{Задача 2.} Пусть $\Omega =\{ a,b,c,d,e,f\} $, ${\rm {\mathbb P}}(\{ a\} )=\ldots ={\rm {\mathbb P}}(\{ f\} )=1/6$ и случайная величина $X:\Omega \to {\mathbb R}$ задана при помощи следующей таблицы.

\begin{tabular}{|p{0.3in}|p{0.3in}|p{0.3in}|p{0.2in}|p{0.3in}|p{0.2in}|p{0.3in}|} \hline 
$\Omega $ & $a$ & $b$ & $c$ & $d$ & $e$ & $f$ \\ \hline 
$X$ & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ \\ \hline 
\end{tabular}

\begin{enumerate}
\item  Найдите $\{ \omega \in \Omega :X(\omega )\ge 3\} $.

\item  Найдите ${\rm {\mathbb P}}(\{ \omega \in \Omega :X(\omega )\ge 3\} )$.

\item  Найдите ${\rm {\mathbb P}}(\{ \omega \in \Omega :X(\omega )<6\} )$.

\item  Постройте графики функций распределения случайных величин $X$, $\cos (\pi X/3)$ и $\sin (\pi X/3)$.

\item  Найдите ${\rm {\mathbb E}}[X]$, ${\rm {\mathbb E}}\cos (\pi X/3)$ и  ${\rm {\mathbb E}}\sin (\pi X/3)$.

\item  Найдите $D(X)$, $D\cos (\pi X/3)$ и $D\sin (\pi X/3)$,

\item  Постройте таблицы распределения случайных величин $X$, $\cos (\pi X/3)$ и $\sin (\pi X/3)$.
\end{enumerate}

\textbf{Таблица 1: таблица тригонометрических функций}

\begin{tabular}{|p{0.4in}|p{0.5in}|p{0.5in}|p{0.5in}|p{0.5in}|p{0.5in}|} \hline 
$\alpha $ & $0$ & $\pi /6$ & $\pi /4$ & $\pi /3$ & $\pi /2$ \\ \hline 
$\cos \alpha $ & $1$ & $\sqrt{3} /2$ & $\sqrt{2} /2$ & $1/2$ & $0$ \\ \hline 
$\sin \alpha $ & $0$ & $1/2$ & $\sqrt{2} /2$ & $\sqrt{3} /2$ & $1$ \\ \hline 
\end{tabular}

\textbf{Задача 3.} Пусть $\Omega =\{ \heartsuit ,\diamondsuit ,\spadesuit ,\clubsuit \} $, ${\rm {\mathbb P}}(\{ \heartsuit \} )=\ldots ={\rm {\mathbb P}}(\{ \clubsuit \} )=1/4$.

Случайные величины $X:\Omega \to {\mathbb R}$ и $Y:\Omega \to {\mathbb R}$ заданы при помощи следующей таблицы.

\begin{tabular}{|p{0.3in}|p{0.3in}|p{0.3in}|p{0.3in}|p{0.3in}|} \hline 
$\Omega $ & ? & ? & ? & ? \\ \hline 
$X$ & $-1$ & $1$ & $-1$ & $1$ \\ \hline 
$Y$ & $1$ & $-1$ & $1$ & $-1$ \\ \hline 
\end{tabular}

Найдите

\begin{enumerate}
\item  Постройте таблицы распределения случайных величин $X$ и $Y$.

\item  Постройте таблицу совместного распределения для $X$ и $Y$.

\item  ${\rm {\mathbb E}}[X]$ и ${\rm {\mathbb E}}[Y]$,

\item  ${\rm {\mathbb E}}[XY]$,

\item  $cov(X,Y)$,

\item  ${\rm {\mathbb E}}[X^{2} ]$ и ${\rm {\mathbb E}}[Y^{2} ]$,

\item  $D(X)$ и $D(Y)$,

\item  $D(XY)$,

\item  $corr(X,Y)$.

\item  Являются ли случайные величины $X$ и $Y$ некоррелированными?

\item  ${\rm {\mathbb P}}(\{ \omega :X(\omega )=1\} )$, ${\rm {\mathbb P}}(\{ \omega :Y(\omega )=1\} )$ и ${\rm {\mathbb P}}(\{ \omega :X(\omega )=1\} \bigcap \{ \omega :Y(\omega )=1\} )$.

\item  Являются ли случайные величины  $X$ и $Y$независимыми?

\item  Постройте графики функций распределения случайных величин $X$ и $Y$.

\item  Найдите $F_{X,Y} (-1,-1)$, $F_{X,Y} (1,-1)$, $F_{X,Y} (-1,1)$, $F_{X,Y} (1,1)$.

\item  Проверьте равенство ${\rm {\mathbb P}}(\{ X\in (-1;1]\} \bigcap \{ Y\in (-1;1]\} )=F_{X,Y} (1,1)-F_{X,Y} (1,-1)-F_{X,Y} (-1,1)+F_{X,Y} (-1,-1)$.
\end{enumerate}

\textbf{Задача 4.} Пусть $\Omega =\left\{\heartsuit ,\diamondsuit ,\spadesuit ,\clubsuit \right\}$, ${\rm {\mathbb P}}\left(\left\{\heartsuit \right\}\right)={\rm {\mathbb P}}\left(\left\{\diamondsuit \right\}\right)={\rm {\mathbb P}}\left(\left\{\spadesuit \right\}\right)={\rm {\mathbb P}}\left(\left\{\clubsuit \right\}\right)={\tfrac{1}{4}} $.

Случайные величины $X$ и $Y$ заданы при помощи следующей таблицы.

\begin{tabular}{|p{0.3in}|p{0.3in}|p{0.3in}|p{0.3in}|p{0.3in}|} \hline 
$\Omega $ & ? & ? & ? & ? \\ \hline 
$X$ & $1$ & $0$ & $1$ & $0$ \\ \hline 
$Y$ & $1$ & $1$ & $0$ & $0$ \\ \hline 
\end{tabular}

Найдите

\begin{enumerate}
\item  Постройте таблицы распределения случайных величин $X$ и $Y$.

\item  Постройте таблицу совместного распределения для $X$ и $Y$.

\item  ${\rm {\mathbb E}}[X]$ и ${\rm {\mathbb E}}[Y]$,

\item  ${\rm {\mathbb E}}[XY]$,

\item  $cov(X,Y)$,

\item  ${\rm {\mathbb E}}[X^{2} ]$ и ${\rm {\mathbb E}}[Y^{2} ]$,

\item  $D(X)$ и $D(Y)$,

\item  $D(XY)$,

\item  $corr(X,Y)$,

\item  Являются ли случайные величины $X$ и $Y$ некоррелированными?

\item  ${\rm {\mathbb P}}(\{ \omega :X(\omega )=1\} )$, ${\rm {\mathbb P}}(\{ \omega :Y(\omega )=1\} )$ и ${\rm {\mathbb P}}(\{ \omega :X(\omega )=1\} \bigcap \{ \omega :Y(\omega )=1\} )$.

\item  Являются ли случайные величины  $X$ и $Y$независимыми?

\item  Постройте графики функций распределения случайных величин $X$ и $Y$.

\item  Найдите $F_{X,Y} (0,0)$, $F_{X,Y} (1,0)$, $F_{X,Y} (0,1)$, $F_{X,Y} (1,1)$.

\item  Проверьте равенство ${\rm {\mathbb P}}(\{ X\in (0;1]\} \bigcap \{ Y\in (0;1]\} )=F_{X,Y} (1,1)-F_{X,Y} (1,0)-F_{X,Y} (0,1)+F_{X,Y} (0,0)$.
\end{enumerate}

\textbf{Задача 5.} Пусть задана таблица совместного распределения случайных величин $X$ и $Y$.

\begin{tabular}{|p{0.4in}|p{0.3in}|p{0.3in}|p{0.3in}|} \hline 
$X\backslash Y$ & $-1$ & $0$ & $1$ \\ \hline 
$-1$ & $0.2$ & $0.1$ & $0.2$ \\ \hline 
$1$ & $0.1$ & $0.3$ & $0.1$ \\ \hline 
\end{tabular}

Найдите

\begin{enumerate}
\item  ${\rm {\mathbb E}}[X]$ и ${\rm {\mathbb E}}[Y]$,

\item  ${\rm {\mathbb E}}[XY]$,

\item  $cov(X,Y)$,

\item  ${\rm {\mathbb E}}[X^{2} ]$ и ${\rm {\mathbb E}}[Y^{2} ]$,

\item  $D(X)$ и $D(Y)$,

\item  $corr(X,Y)$.

\item  Постройте графики функций распределения случайных величин $X$ и $Y$.

\item  Являются ли случайные величины  $X$ и $Y$независимыми?

\item  Найдите $F_{X,Y} (-1,0)$, $F_{X,Y} (-1,1)$, $F_{X,Y} (0,0)$, $F_{X,Y} (0,1)$.

\item  Проверьте равенство ${\rm {\mathbb P}}(\{ X\in (-1;0]\} \bigcap \{ Y\in (0;1]\} )=F_{X,Y} (0,1)-F_{X,Y} (0,0)-F_{X,Y} (-1,1)+F_{X,Y} (-1,0)$.
\end{enumerate}

\textbf{Задача 6.} Пусть задана таблица совместного распределения случайных величин $X$ и $Y$.

\begin{tabular}{|p{0.4in}|p{0.3in}|p{0.3in}|p{0.3in}|} \hline 
$X\backslash Y$ & $-1$ & $0$ & $1$ \\ \hline 
$-1$ & $0.2$ & $0.3$ & $0.1$ \\ \hline 
$1$ & $0.1$ & $0.0$ & $0.3$ \\ \hline 
\end{tabular}

Найдите

\begin{enumerate}
\item  ${\rm {\mathbb E}}[X]$ и ${\rm {\mathbb E}}[Y]$,

\item  ${\rm {\mathbb E}}[XY]$ и ${\rm {\mathbb E}}[Y/X]$

\item  $cov(X,Y)$,

\item  ${\rm {\mathbb E}}[X^{2} ]$ и ${\rm {\mathbb E}}[Y^{2} ]$,

\item  $D(X)$ и $D(Y)$,

\item  $corr(X,Y)$.

\item  Постройте графики функций распределения случайных величин $X$ и $Y$. 

\item  Являются ли случайные величины  $X$ и $Y$независимыми?

\item  Найдите $F_{X,Y} (-1,0)$, $F_{X,Y} (-1,1)$, $F_{X,Y} (0,0)$, $F_{X,Y} (0,1)$.

\item  Проверьте равенство ${\rm {\mathbb P}}(\{ X\in (-1;0]\} \bigcap \{ Y\in (0;1]\} )=F_{X,Y} (0,1)-F_{X,Y} (0,0)-F_{X,Y} (-1,1)+F_{X,Y} (-1,0)$.
\end{enumerate}

\textbf{Задача 7.} Пусть $\Omega =\{ \heartsuit ,\diamondsuit ,\spadesuit ,\clubsuit \} $, ${\rm {\mathbb P}}(\{ \heartsuit \} )=\ldots ={\rm {\mathbb P}}(\{ \clubsuit \} )=1/4$.

Случайные величины $X:\Omega \to {\mathbb R}$ и $Y:\Omega \to {\mathbb R}$ заданы при помощи следующей таблицы.

\begin{tabular}{|p{0.3in}|p{0.3in}|p{0.3in}|p{0.3in}|p{0.3in}|} \hline 
$\Omega $ & ? & ? & ? & ? \\ \hline 
$X$ & $-1$ & $1$ & $-1$ & $1$ \\ \hline 
$Y$ & $1$ & $-1$ & $1$ & $-1$ \\ \hline 
\end{tabular}

Постройте таблицу 

\begin{enumerate}
\item  распределения случайной величины $X$,

\item  распределения случайной величины $Y$,

\item  совместного распределения случайных величин $X$ и $Y$.
\end{enumerate}

\textbf{Задача 8.} Пусть $\Omega =\{ \heartsuit ,\diamondsuit ,\spadesuit ,\clubsuit \} $, ${\rm {\mathbb P}}(\{ \heartsuit \} )=\ldots ={\rm {\mathbb P}}(\{ \clubsuit \} )=1/4$.

Случайные величины $X:\Omega \to {\mathbb R}$ и $Y:\Omega \to {\mathbb R}$ заданы при помощи следующей таблицы.

\begin{tabular}{|p{0.3in}|p{0.3in}|p{0.3in}|p{0.3in}|p{0.3in}|} \hline 
$\Omega $ & ? & ? & ? & ? \\ \hline 
$X$ & $1$ & $0$ & $1$ & $0$ \\ \hline 
$Y$ & $1$ & $1$ & $0$ & $0$ \\ \hline 
\end{tabular}

Постройте таблицу 

\begin{enumerate}
\item  распределения случайной величины $X$,

\item  распределения случайной величины $Y$,

\item  совместного распределения случайных величин $X$ и $Y$.
\end{enumerate}

\textbf{Задача 9.} Пусть ${\rm {\mathbb E}}X=1$, ${\rm {\mathbb E}}Y=2$, ${\rm D}X=3$, ${\rm D}Y=4$, $cov(X,Y)=-1$. Найдите

\begin{enumerate}
\item  ${\rm {\mathbb E}}(2X-Y)$ и ${\rm {\mathbb E}}(2X+Y-4)$,

\item  ${\rm D}(2X)$ и ${\rm D}(3Y+3)$,

\item  ${\rm D}(X+Y)$ и ${\rm D}(X-Y)$,

\item  ${\rm D}(2X+3Y)$ и ${\rm D}(2X-3Y+1)$,

\item  $cov(X+Y,X-Y)$ и $cov(X+2Y+1,3X-Y-1)$,

\item  $corr(X,Y)$ и $corr(X+Y,X-Y)$,

\item  Ковариационную матрицу случайного вектора $Z=(\begin{array}{cc} {X} & {Y} \end{array})$.
\end{enumerate}

\textbf{Задача 10.} Пусть ${\rm {\mathbb E}}X=-1$, ${\rm {\mathbb E}}Y=2$, ${\rm D}X=1$, ${\rm D}Y=2$, $cov(X,Y)=1$. Найдите

\begin{enumerate}
\item  ${\rm {\mathbb E}}(2X+Y)$ и ${\rm {\mathbb E}}(2X+Y-4)$,

\item  ${\rm D}(2X)$ и ${\rm D}(2Y+1)$,

\item  ${\rm D}(X+Y)$ и ${\rm D}(X-Y)$,

\item  ${\rm D}(2X+3Y)$ и ${\rm D}(2X-3Y+1)$,

\item  $cov(X+Y,X-Y)$ и $cov(3X+Y+1,X-2Y-1)$,

\item  $corr(X,Y)$ и $corr(X+Y,X-Y)$,

\item  Ковариационную матрицу случайного вектора $Z=(\begin{array}{cc} {X} & {Y} \end{array})$.

\item \textbf{Задача 11. }Пусть $X_{1} ,X_{2} ,X_{3} $  --- случайные величины такие, что $DX_{1} =4$, $DX_{2} =3$, $DX_{3} =2$, $cov(X_{1} ,X_{2} )=1$, $cov(X_{1} ,X_{3} )=0$, $cov(X_{2} ,X_{3} )=-1$. Найдите $D(X_{1} +X_{2} +X_{3} )$,

\item  $D(X_{1} -X_{3} -1)$,

\item  $D(X_{1} +X_{2} -X_{3} )$,

\item  $D(4X_{1} +3X_{2} +2X_{3} )$,

\item  $D(X_{1} +3X_{3} -10)$,

\item  $D(X_{1} -X_{3} -2X_{2} )$,

\item  $cov(X_{1} +X_{2} ,X_{2} +X_{3} )$,

\item  $cov(X_{1} +X_{2} ,X_{2} -X_{3} )$,

\item  $cov(X_{1} +X_{2} ,X_{2} -X_{1} )$,

\item  $cov(X_{1} +X_{2} ,X_{2} -X_{3} +1)$.
\end{enumerate}

\textbf{Ответ:}

\begin{enumerate}
\item  9,

\item  6,

\item  13,

\item  111,

\item  22,

\item  10,

\item  3,

\item  5,

\item  $-1$,

\item  5.

\item \textbf{Задача 12. }Пусть $X=(\begin{array}{ccc} {X_{1} } & {X_{2} } & {X_{3} } \end{array})$ --- случайный вектор и $V\left(X\right)=\left(\begin{array}{ccc} {4} & {-1} & {0} \\ {-1} & {3} & {-1} \\ {0} & {-1} & {2} \end{array}\right)$ --- его ковариационная матрица. Найдите $D(X_{1} +X_{2} +X_{3} )$,

\item  $D(X_{1} -X_{3} -1)$,

\item  $D(X_{1} +X_{2} -X_{3} )$,

\item  $D(4X_{1} +3X_{2} +2X_{3} )$,

\item  $D(X_{1} +3X_{3} -10)$,

\item  $D(X_{1} -X_{3} -2X_{2} )$,

\item  $cov(X_{1} +X_{2} ,X_{2} +X_{3} )$,

\item  $cov(X_{1} +X_{2} ,X_{2} -X_{3} )$,

\item  $cov(X_{1} +X_{2} ,X_{2} -X_{1} )$,

\item  $cov(X_{1} +X_{2} ,X_{2} -X_{3} +1)$.\textbf{Ответ:} 5,

\item  6,

\item  9,

\item  63,

\item  22,

\item  18,

\item  1,

\item  3,

\item  -1,

\item  3.
\end{enumerate}

 

\begin{enumerate}
\item \textbf{Задача 13. }Пусть $X=(\begin{array}{ccc} {X_{1} } & {X_{2} } & {X_{3} } \end{array})$ --- случайный вектор и $V\left(X\right)=\left(\begin{array}{ccc} {2} & {-1} & {0} \\ {-1} & {2} & {1} \\ {0} & {1} & {1} \end{array}\right)$ --- его ковариационная матрица. Найдите $D(X_{1} +X_{2} +X_{3} )$,

\item  $D(X_{1} -X_{3} -1)$,

\item  $D(X_{1} +X_{2} -X_{3} )$,

\item  $D(4X_{1} +3X_{2} +2X_{3} )$,

\item  $D(X_{1} +3X_{3} -10)$,

\item  $D(X_{1} -X_{3} -2X_{2} )$,

\item  $cov(X_{1} +X_{2} ,X_{2} +X_{3} )$,

\item  $cov(X_{1} +X_{2} ,X_{2} -X_{3} )$,

\item  $cov(X_{1} +X_{2} ,X_{2} -X_{1} )$,
\end{enumerate}

 $cov(X_{1} +X_{2} ,X_{2} -X_{3} +1)$.\textbf{Ответ:}



6

Кафедра математической экономики и эконометрики НИУ ВШЭ. Борзых Д. А.



\begin{enumerate}
\item  5,

\item  3,

\item  1,

\item  42,

\item  11,

\item  19,

\item  2,

\item  0,

\item  0,

\item  0.
\end{enumerate}

\textbf{Задача 14.} Пусть $\Omega =\{ 1,\; 2,\; 3,\; 4\} $, ${\rm {\mathbb P}}(\{ 1\} )=\ldots ={\rm {\mathbb P}}(\{ 4\} )=1/4$, 

$X(\omega )=\cos (\pi \omega /2)$ и $Y(\omega )=\sin (\pi \omega /2)$. Найдите

\begin{enumerate}
\item \begin{enumerate}
\item  ${\rm {\mathbb P}}(\{ X>0\} )$, ${\rm {\mathbb P}}(\{ X\ge 0\} )$, ${\rm {\mathbb P}}(\{ |X|\, =1\} )$ и ${\rm {\mathbb P}}(\{ X\ge Y\} )$, 

\item  ${\rm {\mathbb E}}X$ и ${\rm {\mathbb E}}Y$,

\item  ${\rm {\mathbb E}}[X^{2} ]$ и ${\rm {\mathbb E}}[Y^{2} ]$,

\item  $DX$ и $DY$,

\item  $F_{X} (x)$ и $F_{Y} (x)$.

\item  Найдите $cov(X,Y)$. Являются ли случайные величины $X$ и $Y$ некоррелированными?

\item  Найдите ${\rm {\mathbb P}}(\{ X=1\} )$, ${\rm {\mathbb P}}(\{ Y=1\} )$ и ${\rm {\mathbb P}}(\{ X=1\} \bigcap \{ Y=1\} )$. Являются ли случайные величины $X$ и $Y$ независимыми?
\end{enumerate}
\end{enumerate}

\textbf{Задача 15.} Пусть $\Omega =\{ 1,\; 2,\ldots ,\; 8\} $, ${\rm {\mathbb P}}(\{ 1\} )={\rm {\mathbb P}}(\{ 2\} )=\ldots ={\rm {\mathbb P}}(\{ 8\} )=1/8$, 

$X(\omega )=\cos (\pi \omega /4)$ и $Y(\omega )=\sin (\pi \omega /4)$. Найдите

\begin{enumerate}
\item  ${\rm {\mathbb P}}(\{ X>0\} )$, ${\rm {\mathbb P}}(\{ X\ge 0\} )$, ${\rm {\mathbb P}}(\{ |X|\, =1\} )$ и ${\rm {\mathbb P}}(\{ X\ge Y\} )$, 

\item  ${\rm {\mathbb E}}X$ и ${\rm {\mathbb E}}Y$,

\item  ${\rm {\mathbb E}}[X^{2} ]$ и ${\rm {\mathbb E}}[Y^{2} ]$,

\item  $DX$ и $DY$,

\item  $F_{X} (x)$ и $F_{Y} (x)$.

\item  Найдите $cov(X,Y)$. Являются ли случайные величины $X$ и $Y$ некоррелированными?

\item  Найдите ${\rm {\mathbb P}}(\{ X=1\} )$, ${\rm {\mathbb P}}(\{ Y=1\} )$ и ${\rm {\mathbb P}}(\{ X=1\} \bigcap \{ Y=1\} )$. Являются ли случайные величины $X$ и $Y$ независимыми?
\end{enumerate}

\textbf{Задача 16.} Пусть ${\rm {\mathbb P}}(\{ Z=1\} )={\rm {\mathbb P}}(\{ Z=2\} )=\ldots ={\rm {\mathbb P}}(\{ Z=6\} )=1/6$, $X=\cos (\pi Z/3)$ и $Y=\sin (\pi Z/3)$. Найдите

\begin{enumerate}
\item  ${\rm {\mathbb P}}(\{ X>0\} )$, ${\rm {\mathbb P}}(\{ X\ge 0\} )$, ${\rm {\mathbb P}}(\{ |X|\, =1\} )$ и ${\rm {\mathbb P}}(\{ X\ge Y\} )$, 

\item  ${\rm {\mathbb E}}X$ и ${\rm {\mathbb E}}Y$,

\item  ${\rm {\mathbb E}}[X^{2} ]$ и ${\rm {\mathbb E}}[Y^{2} ]$,

\item  $DX$ и $DY$,

\item  $F_{X} (x)$ и $F_{Y} (x)$.

\item  Найдите $cov(X,Y)$. Являются ли случайные величины $X$ и $Y$ некоррелированными?

\item  Найдите ${\rm {\mathbb P}}(\{ X=1\} )$, ${\rm {\mathbb P}}(\{ Y=1\} )$ и ${\rm {\mathbb P}}(\{ X=1\} \bigcap \{ Y=1\} )$. Являются ли случайные величины $X$ и $Y$ независимыми?
\end{enumerate}

\textbf{Задача 17.} Пусть ${\rm {\mathbb P}}(\{ Z=1\} )={\rm {\mathbb P}}(\{ Z=2\} )=\ldots ={\rm {\mathbb P}}(\{ Z=8\} )=1/8$, $X=\cos (\pi Z/4)$ и $Y=\sin (\pi Z/4)$. Найдите

\begin{enumerate}
\item  ${\rm {\mathbb P}}(\{ X>0\} )$, ${\rm {\mathbb P}}(\{ X\ge 0\} )$, ${\rm {\mathbb P}}(\{ |X|\, =1\} )$ и ${\rm {\mathbb P}}(\{ X\ge Y\} )$, 

\item  ${\rm {\mathbb E}}X$ и ${\rm {\mathbb E}}Y$,

\item  ${\rm {\mathbb E}}[X^{2} ]$ и ${\rm {\mathbb E}}[Y^{2} ]$,

\item  $DX$ и $DY$,

\item  $F_{X} (x)$ и $F_{Y} (x)$.

\item  Найдите $cov(X,Y)$. Являются ли случайные величины $X$ и $Y$ некоррелированными?

\item  Найдите ${\rm {\mathbb P}}(\{ X=1\} )$, ${\rm {\mathbb P}}(\{ Y=1\} )$ и ${\rm {\mathbb P}}(\{ X=1\} \bigcap \{ Y=1\} )$. Являются ли случайные величины $X$ и $Y$ независимыми?
\end{enumerate}

\textbf{Задача 18.} Найдите значение $x\in {\mathbb R}$, при котором функция $Q(x)={\rm {\mathbb E}}\left[(X-x)^{2} \right]$ принимает наименьшее значение. Чему равно значение функции $Q$ в точке минимума?

\textbf{Задача 19*.} Пусть заданы случайные величины $X_{1} ,\ldots ,X_{n} $ такие, что ${\rm {\mathbb E}}X_{i} =\mu $, $DX_{i} =\sigma ^{2} $, $cov(X_{i} ,X_{j} )=0$ при $i\ne j$. Найдите ${\rm {\mathbb E}}\bar{X}$ и $D\bar{X}$, если $\bar{X}:={\tfrac{X_{1} +\ldots +X_{n} }{n}} $.

\textbf{Задача 20*.} Пусть заданы числа $a_{1} ,\ldots ,a_{n} $ и $\sigma ^{2} $, и случайные величины $X_{1} ,\ldots ,X_{n} $ таковы, что ${\rm {\mathbb E}}X_{i} =0$, $DX_{i} =\sigma ^{2} $, $cov(X_{i} ,X_{j} )=0$ при $i\ne j$. Пусть $Y_{i} =a_{i} +X_{i} $, $i=1,\ldots ,n$. Найдите ${\rm {\mathbb E}}Z$ и $DZ$, если

\begin{enumerate}
\item  $Z=Y_{1} $,

\item  $Z={\tfrac{1}{2a_{1} }} Y_{1} +{\tfrac{1}{2a_{2} }} Y_{2} $,

\item  $Z={\tfrac{Y_{1} +\ldots +Y_{n} }{a_{1} +\ldots +a_{n} }} $,

\item  $Z={\tfrac{a_{1} Y_{1} +\ldots +a_{n} Y_{n} }{a_{1}^{2} +\ldots +a_{n}^{2} }} $,

\item  $Z={\tfrac{\sum _{i=1}^{n}(a_{i} -\bar{a})(Y_{i} -\bar{Y}) }{\sum _{i=1}^{n}(a_{i} -\bar{a})^{2}  }} $.
\end{enumerate}

\textbf{Задача 21.} Найдите функцию распределения случайной величины $X:\Omega \to {\mathbb R}$, если её таблица распределения имеет вид

\begin{tabular}{|p{0.4in}|p{0.5in}|p{0.5in}|p{0.5in}|p{0.5in}|} \hline 
       (a) & $X$ & $-1$ & $0$ & $1$ \\ \hline 
\underbar{} & ${\rm {\mathbb P}}_{X} $ & $1/4$ & $1/2$ & $1/4$ \\ \hline 
\end{tabular}



\begin{tabular}{|p{0.4in}|p{0.5in}|p{0.5in}|p{0.5in}|p{0.5in}|} \hline 
       (b) & $X$ & $0$ & $1$ & $2$ \\ \hline 
\underbar{} & ${\rm {\mathbb P}}_{X} $ & $1/4$ & $1/2$ & $1/4$ \\ \hline 
\end{tabular}

\textbf{Задача 22.} Пусть $\Omega =\{ 1,2,3,4,5,6\} $, ${\rm {\mathbb P}}(\{ 1\} )=\ldots ={\rm {\mathbb P}}(\{ 6\} )=1/6$ и случайная величина $X:\Omega \to {\mathbb R}$ задана при помощи таблицы 

\begin{tabular}{|p{0.3in}|p{0.3in}|p{0.3in}|p{0.2in}|p{0.3in}|p{0.2in}|p{0.3in}|} \hline 
$\Omega $ & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ \\ \hline 
$X$ & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ \\ \hline 
\end{tabular}

Найдите $corr({\rm {\mathbb I}}_{\{ X=1\} } ,{\rm {\mathbb I}}_{\{ X=6\} } )$.



