---
title: "Шпаргалка по теории вероятностей"
author: "Добрый Ээх"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output:
  pdf_document: 
    keep_tex: yes
    latex_engine: xelatex
  html_document: default
language: ru-RU
mainfont: "Linux Libertine O"
monofont: "Linux Libertine O"
sansfont: "Linux Libertine O"
fontsize: 11pt
geometry: left=2cm, right=2cm, top=2cm, bottom=2cm
---

# Характеристики случайных величин

## Математическое ожидание величины $R$, $E(R)$

Интуитивно: среднее арифметическое значение величины при многократном повторении случайного эксперимента

Формально: 

- для дискретных величин: $E(R)=\sum_{r} r\cdot P(R=r)$
- для непрерывных величин: $E(R)=\int_{-\infty}^{+\infty} r\cdot f(r) \; dr$, где $f(r)$ --- функция плотности величины $R$

Свойства:

- $E(R) \in \mathbb{R}$
- $E(aR+b)=aE(R)+b$
- $E(R+S)=E(R)+E(S)$

Иногда обозначается $M(R)$

## Дисперсия величины $R$, $Var(R)$

Интуитивно: мера разброса случайной величины

Формально: $Var(R)=E((R-E(R))^2) = E(R^2) - (E(R))^2$.

Геометрический смысл: квадрат длины случайной величины

Свойства:

- $Var(R) \geq 0$
- $Var(R) = 0$ равносильно тому, что $P(R=const)=1$
- $Var(aR+b)=a^2Var(R)$
- $Var(R+S)=Var(R)+Var(S)+2Cov(R,S)$
- $Var(aR+bS)=a^2Var(R)+b^2Var(S)+2abCov(R,S)$
- $Var(R+S)=Var(R)+Var(S)$ если величины линейно независимы

Иногда обозначается $D(R)$

## Стандартное отклонение величины $R$, $\sigma_R$

Интуитивно: мера разброса случайной величины

Формально: $\sigma_R=\sqrt{Var(R)}$.

Геометрический смысл: длина случайной величины

Свойства:

- $\sigma_R \geq 0$
- $\sigma_R = 0$ равносильно тому, что $P(R=const)=1$
- $\sigma_{aR+b}=|a|\sigma_R$


## Ковариация величин $R$ и $S$, $Cov(R,S)$

Интуитивно: мера линейной связи величин $R$ и $S$

Формально: $Cov(R,S)=E((R-E(R))(S-E(S))) = E(RS) - E(R)E(S)$.

Геометрический смысл: скалярное произведение случайных величин

Свойства:

- $Cov(R,S) \in \mathbb{R}$
- $Cov(R,S)=0$ означает отсутствие линейной зависимости между $R$ и $S$
- $Cov(R,S) = Cov(S, R)$
- $Cov(aR+b, S)=aCov(R, S)$
- $Cov(R_1 + R_2, S) = Cov(R_1, S) + Cov(R_2, S)$
- $Cov(R, S_1 + S_2) = Cov(R, S_1) + Cov(R, S_2)$

## Корреляция величин $R$ и $S$, $Corr(R,S)$

Интуитивно: отнормированная мера линейной связи величин $R$ и $S$

Формально: $Corr(R,S)=\frac{Cov(R,S)}{\sqrt{Var(R)Var(S)}}$.

Геометрический смысл: косинус угла между случайными величинами

Свойства:

- $Corr(R,S) \in [-1;1]$
- $Corr(R,S)=0$ означает отсутствие линейной зависимости между $R$ и $S$
- $Corr(R,S) = Corr(S, R)$
- $Corr(aR+b, S)=Corr(R, S)$ при $a>0$

# Основные распределения

## Равномерное на отрезке $[a;b]$, $R \sim U[a;b]$.

Пример ситуации, где возникает: остаток при округлении чисел

Функция плотности: 
\begin{equation}
f(r) = \begin{cases}
1/(b-a), \;  \text{если} \; r \in [a;b] \\
0, \; \text{иначе}
\end{cases}
\end{equation}

Функция плотности в R: `dunif(r, min = a, max = b)`

Функция распределения: 
\begin{equation}
F(r) = \begin{cases}
0, \; \text{если} \; r < a \\
(r-a)/(b-a), \;  \text{если} \; r \in [a;b] \\
1, \; \text{если} \; r > b \\
\end{cases}
\end{equation}

Функция распределения в R: `punif(r, min = a, max = b)`

Свойства:

- $E(R) = (a+b)/2$
- $Var(R) = (a-b)^2/12$

## Нормальное с математическим ожиданием $\mu$ и дисперсией $\sigma^2$, $R \sim N(\mu; \sigma^2)$.

Пример ситуации, где возникает: нахождение суммы или среднего большого количества независимых одинаково распределенных величин

Функция плотности: 
\begin{equation}
f(r) = \frac{1}{\sqrt{2\pi\sigma^2}}\exp\left( -\frac{1}{2\sigma^2}(r-\mu)^2\right)
\end{equation}

Функция плотности в R: `dnorm(r, mean = `$\;\mu$`, sd = `$\;\sigma$`)`

Функция распределения: 
\begin{equation}
F(r) = \int_{-\infty}^r f(t) \; dt
\end{equation}

Функция распределения в R: `pnorm(r, mean = `$\;\mu$`, sd = `$\;\sigma$`)`

Свойства:

- $E(R) = \mu$
- $Var(R) = \sigma^2$




