---
title: "Домашка"
date: ""
output: pdf_document
lang: ru-RU
---

### Задача раз
Известно, что  $X_{i}$ независимы и нормальны, $N\left(\mu ;900\right)$.
Исследователь проверяет гипотезу $H_{0}$: $\mu =10$  против
$H_{A}$: $\mu =30$  по выборке из 20 наблюдений. Критерий выглядит
следующим образом: если  $\bar{X}>c$ , то выбрать  $H_{A} $ ,
иначе выбрать  $H_{0} $.
\begin{enumerate}
\item  Рассчитайте вероятности ошибок
первого и второго рода, мощность критерия для $c=25$.
\item Что произойдет с указанными вероятностями при росте количества
наблюдений если известно что $c\in(10;30)$?
\item Каким должно быть $c$, чтобы вероятность ошибки второго рода
равнялась $0,15$?
\end{enumerate}

### Задача два
Экзамен принимают два преподавателя, случайным образом выбирая студентов. По выборке из 85 и 100 наблюдений, выборочные доли не сдавших экзамен студентов составили соответственно 0.2  и 0.17.
\begin{enumerate}
\item Можно ли при уровне значимости в 1\% утверждать, что преподаватели предъявляют к студентам одинаковый уровень требований?
\item Найдите P-значение.
\end{enumerate}


### Задача три
При расчете страхового тарифа страховая компания предполагает, что вероятность наступления страхового случая 0.005. По итогам прошедшего года из 10000 случайно выбранных договоров страховых случаев наблюдалось 67.
\begin{enumerate}
\item Согласуются ли полученные данные с предположением страховой компании? (Альтернатива: вероятность страхового случая больше)
\item Найдите P-значение.
\end{enumerate}
