---
output: pdf_document
lang: ru-RU
---

7. Величины $X_1$, $X_2$, \ldots независимы и имеют одинаковую функцию плотности
\[
f(x) = \begin{cases}
5h\exp(-5hx), \text{ если } x\geq 0 \\
0, \text{ иначе }
\end{cases}.
\]

Оказалось, что $X_1=3$, $X_2=8$. Найдите $\hat h_{MM}$, $\hat h_{ML}$.

1. Величины $X_1$, $X_2$, \ldots независимы и имеют одинаковую функцию плотности
\[
f(x) = \begin{cases}
2a\exp(-2ax), \text{ если } x\geq 0 \\
0, \text{ иначе }
\end{cases}.
\]

Оказалось, что $X_1=3$, $X_2=5$. Найдите $\hat a_{MM}$, $\hat a_{ML}$.

2. Величины $X_1$, $X_2$, \ldots независимы и имеют одинаковую функцию плотности
\[
f(x) = \begin{cases}
3b\exp(-3bx), \text{ если } x\geq 0 \\
0, \text{ иначе }
\end{cases}.
\]

Оказалось, что $X_1=4$, $X_2=5$. Найдите $\hat b_{MM}$, $\hat b_{ML}$.

3. Величины $X_1$, $X_2$, \ldots независимы и имеют одинаковую функцию плотности
\[
f(x) = \begin{cases}
4c\exp(-4cx), \text{ если } x\geq 0 \\
0, \text{ иначе }
\end{cases}.
\]

Оказалось, что $X_1=1$, $X_2=5$. Найдите $\hat c_{MM}$, $\hat c_{ML}$.

4. Величины $X_1$, $X_2$, \ldots независимы и имеют одинаковую функцию плотности
\[
f(x) = \begin{cases}
(d-1)\exp(-dx+x), \text{ если } x\geq 0 \\
0, \text{ иначе }
\end{cases}.
\]

Оказалось, что $X_1=3$, $X_2=4$. Найдите $\hat d_{MM}$, $\hat d_{ML}$.

5. Величины $X_1$, $X_2$, \ldots независимы и имеют одинаковую функцию плотности
\[
f(x) = \begin{cases}
(f-2)\exp(-fx+2x), \text{ если } x\geq 0 \\
0, \text{ иначе }
\end{cases}.
\]

Оказалось, что $X_1=2$, $X_2=5$. Найдите $\hat f_{MM}$, $\hat f_{ML}$.

6. Величины $X_1$, $X_2$, \ldots независимы и имеют одинаковую функцию плотности
\[
f(x) = \begin{cases}
(g-3)\exp(-gx+3x), \text{ если } x\geq 0 \\
0, \text{ иначе }
\end{cases}.
\]

Оказалось, что $X_1=7$, $X_2=5$. Найдите $\hat g_{MM}$, $\hat g_{ML}$.

