---
title: "Теория вероятностей и статистики: Медиана! "
date: "2018-02-06, 18:10"
output:
  pdf_document:
    toc: false
    toc_depth: 2
    keep_tex: yes
    number_sections: false
    fig_width: 4
    fig_height: 3
    fig_caption: true
    highlight: tango
    latex_engine: xelatex
  word_document: default
  html_document: default
lang: ru-RU
mainfont: Arial
fontsize: 11pt
geometry: left=2cm, right=2cm, top=2cm, bottom=2cm
documentclass: article
linkcolor: blue
urlcolor: blue
citecolor: blue
header-includes:
- \newfontfamily{\cyrillicfonttt}{Arial}
- \newfontfamily{\cyrillicfont}{Arial}
- \newfontfamily{\cyrillicfontsf}{Arial}
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
library(tikzDevice) # конвертация графиков в tikz-код
# library(azbuka) # настройка конвертации графиков в tikz-код
azbuka::tikzsetup()
library(tidyverse) # манипуляции с данными и графики
```


## Медиана

Медиана — научно-популярный праздник по теории вероятностей и математической статистике. Для студентов исследовательского потока участие обязательное, для студентов базового — добровольное :)

Дата и время: 2018 год, 6 февраля, 18:10.

Место: Шаболовка 26. Аудитории будут чуть позже.

## Что делать?

1. Разбиться на команды по 4 человека. В редких случаях по согласованию с кураторами разрешены команды в 5 человек. 

2. Зарегистрировать свою команду и выбрать куратора на [goo.gl/4jgm46](goo.gl/4jgm46). 

Далее можно и полезно советоваться с куратором :)

3. Придумать презентацию научного сюжета из области теории вероятностей, математической статистики или анализа данных. 

Презентация может включать самостоятельное изготовление ценного артефакта в духе доски Гальтона.

4. Придумать несколько простых задач, прямо или косвенно связанных с сюжетом станции.

5. Организовать проведение своей станции на Медиану.


## Как будет проходить?

Медиана проходит в два раунда по одному часу. В течение первого часа половина команды презентует свою станцию, а половина посещает другие станции. В течение второго часа половины команды меняются ролями.

Хозяева станции презентуют гостям свой сюжет и предлагают решить одну простую задачку. Успешно решившим гостям хозяева выдают несколько конфеток. Конфетки выдаются в начале раунда организаторами всем станциям в равных количествах.

## Что мне за это будет?

Количество собранных конфет никак не влияет на балл по теории вероятностей и статистики. В зависимости от числа конфет можно будет претендовать на ценные и бесценные призы :)   

## Примеры для вдохновения

1. Доска Гальтона, [youtu.be/9xUBhhM4vbM](https://youtu.be/9xUBhhM4vbM)

2. Танцы про алгоритмы сортировки, [youtu.be/ywWBy6J5gz8](https://youtu.be/ywWBy6J5gz8)

3. Вероятностная ДНК, [goo.gl/u76Teg](goo.gl/u76Teg)


